# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

elasticsearch:
  rest:
    uris: http://localhost:9200

server:
  port: 8080
